### ISSUE TITLE
Create a liveliness endpoint for all apps

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/demo-projects#484]
All the apps need to start with a base template, which should have a default liveliness check endpoint for deployments. 

For instance, every app should implement a `/status/ping`, and that should return an HTTP error code of 200 with a response of `{ "msg" : "pong" }`

This issue may be split into multiple PRs, with one PR for every project.

```[tasklist]
### Tasks
- [x] 25--5-clock (#486)
- [x] american-british-translator (#498)
- [x] anonymous-message-board (#512)
- [x] bar-chart (#513)
- [x] build-a-pinterest-clone (#514)
- [x] cash-register (#487)
- [x] chart-the-stock-market (#516)
- [x] choropleth-map (#517)
- [x] drum-machine (#488)
- [x] exercise-tracker (#518)
- [x] file-metadata-microservice (#499)
- [x] forum-proxy (#500)
- [x] heat-map (#525)
- [x] image-search-abstraction-layer (#526)
- [x] issue-tracker (#527)
- [x] javascript-calculator (#491)
- [x] manage-a-book-trading-club (#530)
- [x] markdown-previewer (#492)
- [x] metric-imperial-converter (#531)
- [x] nightlife-coordination-app (Note: we don't have an example app for this project)
- [x] p2p-video-chat-application (#529)
- [x] palindrome-checker (#495)
- [x] personal-library (#532)
- [x] personal-portfolio (#533)
- [x] pokeapi-proxy (#496)
- [x] pokemon-search-app (#534)
- [x] product-landing-page (#537)
- [x] random-quote-machine (#493)
- [x] request-header-parser-microservice (#540)
- [x] roman-numeral-converter (#539)
- [X] scatterplot-graph (#542)
- [x] secure-real-time-multiplayer-game (#503)
- [x] stock-price-checker-proxy (#507)
- [X] stock-price-checker (#543)
- [X] sudoku-solver (#544)
- [x] survey-form (#515)
- [X] technical-documentation-page (#546)
- [X] telephone-number-validator (#547)
- [x] timestamp-microservice (#524)
- [X] treemap-diagram (#548)
- [x] tribute-page (#494)
- [x] twitch-proxy (#522)
- [x] url-shortener-microservice (#523)
- [x] voting-app (#519)
- [x] weather-proxy (#511)
```

**Comment by leonfeng** [comment]
Oops, sorry for causing the accidental closure.

**Comment by naomi-lgbt** [comment]
Woohoo!!!!

Thanks to all of our contributors who helped get this done~!

**Comment by a2937** [comment]
It's time to close this issue. :)
